name: skript-website

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Checkout submodules
      run: |
        git submodule init
        git submodule update

    - name: Setup NodeJS environement
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Restore cache
    - uses: actions/cache@v1
      id: cache-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn
        restore-keys: |
          ${{ runner.os }}-yarn

    - name: Install dependencies
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install

    - name: Build Website
      run: yarn export
    
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@master
      env:
        EMAIL: ${{ secrets.EMAIL }}
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BUILD_DIR: __sapper__/export